#!/usr/bin/env python3
"""Rasterise 16x16 bitmaps for Hangul + Japanese kana/kanji into a C header for the player.

Sources (both OFL, attribution in the header):
  Nanum Gothic  - Korean
  Noto Sans JP  - Japanese
FreeType's monochrome mode is used rather than thresholding an anti-aliased render: at 16px
the hinted mono output keeps thin strokes that thresholding drops (a thresholded 日 lost its
middle bars entirely).
"""
from PIL import Image, ImageFont

BOX = 16

def loader(path, size):
    f = ImageFont.truetype(path, size)
    def glyph(ch):
        m = f.getmask(ch, mode='1')
        if m.size[0] == 0 or m.size[1] == 0:
            return None
        im = Image.frombytes('L', m.size, bytes(m))
        bb = im.getbbox()
        if not bb:
            return None
        im = im.crop(bb)
        if im.width > BOX or im.height > BOX:
            im.thumbnail((BOX, BOX))
        out = Image.new('L', (BOX, BOX), 0)
        out.paste(im, ((BOX - im.width) // 2, (BOX - im.height) // 2))
        rows = []
        for r in range(BOX):
            v = 0
            for c in range(BOX):
                if out.getpixel((c, r)):
                    v |= 1 << (15 - c)          # MSB = leftmost pixel
            rows.append(v)
        return rows
    return glyph

def emit(f, name, glyphs):
    f.write(f'static const unsigned short {name}[][{BOX}] = {{\n')
    for cp, rows in glyphs:
        f.write('  {' + ','.join(f'0x{v:04X}' for v in rows) + f'}},  /* U+{cp:04X} */\n')
    f.write('};\n')

kr = loader('NanumGothic-Regular.ttf', 16)
jp = loader('NotoSansJP%5Bwght%5D.ttf', 16)

hangul = []
for cp in range(0xAC00, 0xD7A4):
    hangul.append((cp, kr(chr(cp)) or [0] * BOX))
print(f'hangul {len(hangul)}', flush=True)

kana = []
for cp in range(0x3000, 0x3100):
    kana.append((cp, jp(chr(cp)) or [0] * BOX))
print(f'kana/punct {len(kana)}', flush=True)

cjk = []
for cp in list(range(0x4E00, 0xA000)) + [0x3005, 0x303B, 0xFF01, 0xFF1F]:
    try:
        chr(cp).encode('shift_jis')            # JIS X 0208 coverage
    except Exception:
        continue
    g = jp(chr(cp))
    if g:
        cjk.append((cp, g))
print(f'cjk {len(cjk)}', flush=True)

with open('font16.h', 'w') as f:
    f.write('/* 16x16 subtitle glyphs: Hangul, kana and JIS X 0208 kanji.\n'
            ' * Rasterised from Nanum Gothic (Korean) and Noto Sans JP (Japanese), both under\n'
            ' * the SIL Open Font License. Rows are 16 bits, most significant bit leftmost.\n'
            ' * Generated by tools/gen_font16.py -- do not edit by hand. */\n'
            '#ifndef MOFLEX_FONT16_H\n#define MOFLEX_FONT16_H\n\n')
    f.write(f'#define FONT16_HANGUL_LO 0x{hangul[0][0]:04X}\n')
    f.write(f'#define FONT16_HANGUL_HI 0x{hangul[-1][0]:04X}\n')
    f.write(f'#define FONT16_KANA_LO   0x{kana[0][0]:04X}\n')
    f.write(f'#define FONT16_KANA_HI   0x{kana[-1][0]:04X}\n\n')
    emit(f, 'font16_hangul', hangul)
    f.write('\n')
    emit(f, 'font16_kana', kana)
    f.write('\n')
    f.write('static const unsigned short font16_cjk_cp[] = {'
            + ','.join(f'0x{cp:04X}' for cp, _ in cjk) + '};\n')
    f.write(f'#define FONT16_CJK_N ((int)(sizeof font16_cjk_cp / sizeof font16_cjk_cp[0]))\n')
    emit(f, 'font16_cjk', cjk)
    f.write('\n#endif\n')
print('wrote font16.h', flush=True)
