#!/usr/bin/env python3
"""Convert an 800x240 parallel stereo PNG into the top-screen RGB565 rotated
framebuffer layout and emit app/source/clownsec_logo.c.
Usage: python3 tools/gen_logo.py <banner.png>"""
import sys
from PIL import Image

W, H = 400, 240
src = sys.argv[1] if len(sys.argv) > 1 else \
    '/Users/brainphreak/Downloads/clownsec-banner-3d-parallel.png'
im = Image.open(src).convert('RGB')
assert im.size == (2 * W, H), im.size
px = im.load()

def eye_bytes(xoff):
    buf = bytearray(W * H * 2)
    for x in range(W):
        for y in range(H):
            r, g, b = px[x + xoff, y]
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)   # RGB565
            idx = (x * H + (H - 1 - y)) * 2                        # rotated fb, LE
            buf[idx] = v & 0xFF
            buf[idx + 1] = (v >> 8) & 0xFF
    return buf

def emit(name, data, f):
    f.write("const unsigned char %s[%d] = {\n" % (name, len(data)))
    for i in range(0, len(data), 24):
        f.write(",".join(str(b) for b in data[i:i + 24]) + ",\n")
    f.write("};\n")

out = 'app/source/clownsec_logo.c'
with open(out, 'w') as f:
    f.write('/* Generated by tools/gen_logo.py. Top-screen RGB565, rotated fb layout. */\n')
    f.write('#include "clownsec_logo.h"\n')
    emit('clownsec_logo_left', eye_bytes(0), f)
    emit('clownsec_logo_right', eye_bytes(W), f)
print("wrote", out)
