#!/usr/bin/env python3
"""Build the 8x16 alphabetic table: Latin (+Extended-A), Greek, Cyrillic, Hebrew.

Primary source is Spleen 8x16 (BSD), a font DRAWN at this size -- rasterising a vector face at
12px and thickening it afterwards gave uneven stems that read as a novelty font. Spleen does not
cover every accented Greek/Cyrillic form, so the remainder is rendered from Noto Sans (OFL) at
the same baseline, unthickened, which is closer in weight than a widened glyph would be.
"""
import re
from PIL import Image, ImageFont

W, H, PX = 8, 16, 12

def load_bdf(path):
    out, cur, cap, rows = {}, None, False, []
    for line in open(path, encoding='latin-1'):
        if line.startswith('ENCODING'): cur = int(line.split()[1])
        elif line.startswith('BITMAP'): rows, cap = [], True
        elif line.startswith('ENDCHAR'):
            if cur is not None and cur >= 0 and len(rows) == H: out[cur] = rows
            cap = False
        elif cap and re.fullmatch(r'[0-9A-Fa-f]{2}\s*', line):
            rows.append(int(line.strip(), 16))
    # BDF rows are MSB-left; the player's tables are LSB-left like font8x8_basic
    return {cp: [int(f'{v:08b}'[::-1], 2) for v in r] for cp, r in out.items()}

spleen = load_bdf('spleen.bdf')
noto = ImageFont.truetype('NotoSans.ttf', PX)

def from_noto(ch):
    try: m, off = noto.getmask2(ch, mode='1')
    except Exception: return None
    if m.size[0] == 0 or m.size[1] == 0: return None
    im = Image.frombytes('L', m.size, bytes(m))
    out = Image.new('L', (W, H), 0)
    out.paste(im, (off[0], off[1]))            # the font's own baseline, never re-centred
    g = [sum(1 << c for c in range(W) if out.getpixel((c, r))) for r in range(H)]
    return g if any(g) else None

ranges = [(0x20, 0x7E), (0xA0, 0xFF), (0x100, 0x17F), (0x386, 0x3CE), (0x400, 0x45F), (0x590, 0x5FF)]
extra = [0x2010, 0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2026, 0x20AC, 0x266A, 0x266B]
out, nspleen, nnoto = [], 0, 0
for cp in [c for lo, hi in ranges for c in range(lo, hi + 1)] + extra:
    g = spleen.get(cp)
    if g and any(g): out.append((cp, g)); nspleen += 1
    else:
        g = from_noto(chr(cp))
        if g: out.append((cp, g)); nnoto += 1
out.sort()

with open('font8x16.h', 'w') as fh:
    fh.write('/* 8x16 alphabetic glyphs: Latin (+Extended-A), Greek, Cyrillic, Hebrew.\n'
             ' * Spleen 8x16 (BSD 2-clause) where it has the glyph, else Noto Sans (OFL) rendered\n'
             ' * at the same baseline. Generated by tools/gen_font8x16.py -- do not edit by hand.\n'
             ' * Rows are 8 bits, LSB leftmost, matching font8x8_basic. 16 tall like the Hangul and\n'
             ' * kanji tables, so a line mixing scripts has ONE glyph height. */\n'
             '#ifndef MOFLEX_FONT8X16_H\n#define MOFLEX_FONT8X16_H\n\n')
    fh.write('static const unsigned short font8x16_cp[] = {'
             + ','.join(f'0x{cp:04X}' for cp, _ in out) + '};\n')
    fh.write('#define FONT8X16_N ((int)(sizeof font8x16_cp / sizeof font8x16_cp[0]))\n')
    fh.write('static const unsigned char font8x16[][16] = {\n')
    for cp, g in out:
        fh.write('  {' + ','.join(f'0x{v:02X}' for v in g) + f'}},  /* U+{cp:04X} */\n')
    fh.write('};\n\n#endif\n')
print(f'{len(out)} glyphs ({nspleen} Spleen, {nnoto} Noto), {len(out)*16/1024:.1f} KB')
